project:
  type: website

website:
  title: "Megha Joshi"
  site-url: https://meghapsimatrix.com
  repo-url: https://github.com/meghapsimatrix/meghapsimatrix_website
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#9D5783"
    right:
      - text: About
        file: index.qmd
      - posts.qmd
      - software.qmd
      - publications.qmd
      - text: Resume
        href: resume/index.qmd
      - icon: github
        href: https://github.com/meghapsimatrix
        

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

