---
title: "Direct ties to a faculty mentor related to positive outcomes for undergraduate researchers"
author: 
  - name:
      given: Megha
      family: Joshi
  - name: 
      given: Melissa L.
      family: Aikens
  - name: 
      given: Erin L.
      family: Dolan
date: 2019-05-08
categories:
- structural equation modeling
citation: 
  type: article-journal
  container-title: BioScience
  doi: 10.1093/biosci/biz039
  url: https://doi.org/10.1093/biosci/biz039
  volume: 69
  issue: 5
  page: 389–397
links:
- text: Journal
  url: https://doi.org/10.1093/biosci/biz039
  icon: newspaper
---

Mentored research is critical for integrating undergraduates into the scientific community. Undergraduate researchers experience a variety of mentoring structures, including dyads (i.e., direct mentorship by faculty) and triads (i.e., mentorship by graduate or postdoctoral researchers \[postgraduates\] and faculty). Social capital theory suggests that these structures may offer different resources that differentially benefit undergraduates. To test this, we collected data from a national sample of more than 1,000 undergraduate life science researchers and used structural equation modeling to identify relationships between mentoring structures and indicators of integration into the scientific community. Undergraduates in dyads and triads with direct faculty interactions reported similar levels of science self-efficacy, scientific identity, and scholarly productivity, and higher levels of these outcomes than students in triads lacking faculty interactions. Undergraduates’ career intentions were unrelated to their mentoring structure, and their gains in thinking and working like scientists were higher if they interacted with both postgraduates and faculty.
