{
  "hash": "03d056e37da6606c75055f7623f8216b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Propensity Score Analysis with Multiply Imputed Data\"\nauthor: \"Megha Joshi\"\ndate: 2020-06-23\ncategories: [\"propensity score\", \"missing data\", \"causal inference\"]\nbibliography: references.bib\ncsl: apa.csl\ndraft: false\n---\n\n\n\nIn this post, I walk through steps of running propensity score analysis when there is missingness in the covariate data. Particularly, I look at multiple imputation and ways to condition on propensity scores estimated with imputed data. The code builds on my earlier [post](https://meghapsimatrix.com/post/missing_dat/) where I go over different ways to handle missing data when conducting propensity score analysis. I go through `tidyeval` way of dealing with multiply imputed data. Please see `MatchThem` package for functions that work with multiply imputed data and propensity scores [@matchthem_2020].\n\n@hill_2004 and @mitra_comparison_2016 examined two distinct ways to condition on the propensity scores estimated on multiply imputed data:\n\n## Multiple Imputation Across (MI Across)\n\nThis approach involves creating *m* imputed datasets and then estimating propensity scores within each of the datasets and then averaging each unit's *m* propensity scores across the *m* datasets [@hill_2004]. Stratification, matching or IPW can be implemented using these averaged propensity scores [@hill_2004]. Outcome models that include covariates will need to use the weights or strata derived from the averaged propensity scores and the *m* sets of covariate values. The weighted regression estimates will then need to be pooled.\n\n## Multiple Imputation Within (MI Within)\n\nThis approach involves creating *m* imputed datasets and then estimating propensity scores within each of the datasets [@hill_2004]. Instead of averaging the propensity scores across the datasets, this method entails conditioning on the propensity scores within the datasets and running the outcome analyses within each dataset [@hill_2004]. The separate regression estimates have to be pooled.\n\n# Read in the data\n\nBelow, I show how to implement the Across and Within methods to estimate the average treatment effect on the treated (ATT). The data that I use here is from [High School Longitudinal Study of 2009](https://nces.ed.gov/surveys/hsls09/index.asp) to analyze the effect of dropping out of high school on later math achievement for students who dropped out. For the purpose of this example, I am going to assume a simple random sample.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mice)\nlibrary(estimatr)\nlibrary(broom)\nlibrary(naniar)\nlibrary(knitr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhsls_dat <- read_csv(\"https://raw.githubusercontent.com/meghapsimatrix/datasets/master/causal/HSLS09_incomplete.csv\") %>%\n  mutate_if(is.character, as.factor) %>%\n  mutate_at(vars(repeated_grade, IEP), as.factor) %>%\n  select(-working_T3) # an outcome we don't care about\n```\n:::\n\n\n\nBelow, using `gg_miss_var` from the `naniar` package, I visualize the percent of data that are missing for each of the variables [@naniar_2020]. The treatment variable, `drop_status` has no missing data. The outcome variable, `math_score_T2`, however, does have around 10% missing data. I am going to impute the outcome data and the covariate data in this example. Please see @hill_2004 for a discussion on dealing with missing outcome data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_miss_var(hsls_dat, show_pct = TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n# Multiple imputation using `mice`\n\nHere, I impute the data using the `mice` package and set the number of imputations and iterations to 10 each [@vanB_2011]. Then, I save the result as an `RData` file that I can load later. For the imputation method, I let mice run the default methods: predicitive mean matching for continuous variables, Bayesian logistic regression for binary variables and Bayesian polytomous regression for multinomial variables. For more information on different methods for imputation, please see [Chapter 6.2](https://stefvanbuuren.name/fimd/sec-modelform.html) from [Flexible Modeling of Missing Data](https://stefvanbuuren.name/fimd/) [@van2018flexible].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsystem.time(temp_data <- mice(hsls_dat, m = 10, maxit = 10, seed = 20200516))\n\nsave(temp_data, file = \"temp_data.RData\")\n```\n:::\n\n\n\n## Imputed data\n\nI load the saved `RData` file and then extract the data that contains each of the 10 imputed data stacked.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"temp_data.RData\")\nimp_dat <- complete(temp_data, action = \"long\")\n```\n:::\n\n\n\n# Estimating propensity scores\n\nBelow I create a dataset with only the covariates and use the `paste()` function to create a propensity score model equation. For the sake of this example, I only focus on including main effects of the covariates in the propensity score model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovs <- imp_dat %>%\n  select(sex:climate, math_score_T1)\n\nequation_ps <- paste(\"drop_status ~ \", paste(names(covs), collapse = \" + \"))\nequation_ps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"drop_status ~  sex + race + language + repeated_grade + IEP + locale + region + SES + math_identity + math_utility + math_efficacy + math_interest + engagement + belonging + expectations + climate + math_score_T1\"\n```\n\n\n:::\n:::\n\n\n\nHere, I create a function `estimate_ps()` that takes in an equation and a dataset and runs logistic regression using `glm()`. The function then adds the logit of propensity scores and the propensity scores as columns in the data.\n\nI then group the `imp_dat` by the imputation number and then run the `estimate_ps()` function on each of the imputed dataset using the `do()` function from `dplyr` [@tidy_2020].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_ps <- function(equation, dat){\n  \n  ps_model <- glm(as.formula(equation), family = binomial, data = dat)\n  \n  dat <- dat %>%\n    mutate(ps_logit = predict(ps_model, type = \"link\"),\n           ps = predict(ps_model, type = \"response\"))\n  \n  return(dat)\n  \n}\n\n\nimp_dat_ps <- imp_dat %>%\n  group_by(.imp) %>%\n  do(estimate_ps(equation_ps, .)) %>%\n  ungroup()\n```\n:::\n\n\n\n# Estimating ATT IPW weights\n\nBelow I estimate ATT weights using the across and within methods. For the Across method, I use the average of the propensity scores across the imputed datasets to calculate weights. For the within method, I use the the propensity scores estimated within each imputed dataset to calculate weights.\n\nThe code below groups the imputed data by `.id` which is an identifier denoting each case. For each case, I summarize the mean of the propensity scores across the 10 imputed dataset and add that mean propensity score as a variable `ps_across` in the data. Then, I estimate the ATT weights using the averaged propensity scores for the Across method and the original propensity scores for the Within method.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimp_dat_ps <- imp_dat_ps %>%\n  group_by(.id) %>%\n  mutate(ps_across = mean(ps)) %>%\n  ungroup() %>%\n  mutate(att_wt_across = drop_status + (1 - drop_status) * ps_across/(1 - ps_across),\n         att_wt_within = drop_status + (1 - drop_status) * ps/(1 - ps))\n\n\nimp_dat_ps %>%\n  select(.imp, ps, ps_across, att_wt_across, att_wt_within)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 214,020 × 5\n    .imp       ps ps_across att_wt_across att_wt_within\n   <int>    <dbl>     <dbl>         <dbl>         <dbl>\n 1     1 0.00339   0.00330       0.00331       0.00340 \n 2     1 0.00989   0.0102        0.0103        0.00999 \n 3     1 0.00135   0.00131       0.00132       0.00135 \n 4     1 0.0119    0.0114        0.0115        0.0120  \n 5     1 0.00222   0.00246       0.00246       0.00222 \n 6     1 0.00289   0.00294       0.00295       0.00290 \n 7     1 0.0113    0.0101        0.0102        0.0114  \n 8     1 0.00347   0.00375       0.00377       0.00348 \n 9     1 0.00327   0.00276       0.00276       0.00328 \n10     1 0.000667  0.000633      0.000633      0.000667\n# ℹ 214,010 more rows\n```\n\n\n:::\n:::\n\n\n\n# Checking common support\n\n## Across\n\nThe propensity scores are averaged across the imputations when using the Across method. Thus, I create a density plot showing the distribution of the logit of the propensity scores from one of the imputations (all of the imputations will have the same distribution). The distribution of the propensity scores for drop-outs overlaps with that for the stayers satisfying the common support assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimp_dat_ps %>%\n  mutate(drop = if_else(drop_status == 1, \"Drop-outs\", \"Stayers\"),\n         ps_across_logit = log(ps_across/ (1 - ps_across))) %>%\n  filter(.imp == 1) %>%\n  ggplot(aes(x = ps_across_logit, fill = drop)) +\n  geom_density(alpha = .5) + \n  labs(x = \"Logit Propensity Scores\", y = \"Density\", fill = \"\") + \n  ggtitle(\"Common Support: Across Method\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=480}\n:::\n:::\n\n\n\n## Within\n\nThe propensity scores estimated for each imputation are used when using the Within method. Below, I create density plots showing distributions of the logit of the propensity scores faceted by the imputation. The common support assumption seems to be satisfied across all the imputations.\n\nIn other datasets, the common support assumption may be violated. In such a case, certain cases might need to be trimmed from the analysis so there is enough overlap of the distributions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimp_dat_ps %>%\n  mutate(drop = if_else(drop_status == 1, \"Drop-outs\", \"Stayers\")) %>%\n  ggplot(aes(x = ps_logit, fill = drop)) +\n  geom_density(alpha = .5) + \n  labs(x = \"Logit Propensity Scores\", y = \"Density\", fill = \"\") + \n  ggtitle(\"Common Support: Within Method\") + \n  facet_wrap(~ .imp, ncol = 2) + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=576}\n:::\n:::\n\n\n\n# Checking balance\n\nAt this point, we would check balance. Please see the `cobalt` package for functions on checking balance on multiply imputed data. I am going to skip this step for now.\n\n# Estimating ATT\n\nBelow I create a function to estimate the ATT. The function takes in an equation, a dataset, and weights as arguments. Then, it runs a model using `lm_robust()` from the `estimatr` package [@estimatr_2020]. The standard errors of the regression coefficients are estimated using `HC2` type sandwich errors. It then cleans up the results using `tidy()` from `broom` [@broom_2020].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_ATT <- function(equation, dat, wts){\n  \n  wts <- dat %>% pull({{wts}})\n  \n  model <- lm_robust(as.formula(equation), data = dat, weights = wts)\n  \n  res <- model %>%\n    tidy() %>%\n    filter(term == \"drop_status\") %>%\n    select(term, estimate, se = std.error, ci_low = conf.low, ci_high = conf.high, df = df)\n  \n  return(res)\n  \n}\n```\n:::\n\n\n\nI set up an equation regressing the outcome variable, `math_score_T2` on drop status and on the main effects of all the covariates. Then, I run the `estimate_ATT()` function on each imputed data using `group_by()` and `do()`. Note that the weights are different for the Across and Within methods.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequation_ancova <- paste(\"math_score_T2 ~ drop_status + \", paste(names(covs), collapse = \" + \"))\nequation_ancova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"math_score_T2 ~ drop_status +  sex + race + language + repeated_grade + IEP + locale + region + SES + math_identity + math_utility + math_efficacy + math_interest + engagement + belonging + expectations + climate + math_score_T1\"\n```\n\n\n:::\n\n```{.r .cell-code}\nacross_res <- imp_dat_ps %>%\n  group_by(.imp) %>%\n  do(estimate_ATT(equation = equation_ancova, dat = ., wts = att_wt_across)) %>%\n  ungroup()\n\nwithin_res <- imp_dat_ps %>%\n  group_by(.imp) %>%\n  do(estimate_ATT(equation = equation_ancova, dat = ., wts = att_wt_within)) %>%\n  ungroup()\n```\n:::\n\n\n\n# Pooling the results\n\nHere, I create a function called `calc_pooled()` using formula by @barnard_small-sample_nodate to pool the results across the imputations. The `mice` package has the `pool()` function to do the same thing but we would need to convert the imputed data back to `mids` object type and I just wanted to skip all that :D\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalc_pooled <- function(dat, est, se, df){\n  \n  dat <- dat %>%\n    mutate(est = dat %>% pull({{est}}),\n           se = dat %>%pull({{se}}),\n           df = dat %>% pull({{df}}))\n  \n  pooled <- dat %>%\n    summarize(m = n(),\n              B = var(est),  # between imputation var\n              beta_bar = mean(est), # mean of estimated reg coeffs\n              V_bar = mean(se^2), # mean of var - hc corrected   within imp var\n              eta_bar = mean(df)) %>%   # mean of df\n    mutate(\n      \n      V_total = V_bar + B * (m + 1) / m,  #between and within var est\n      gamma = ((m + 1) / m) * B / V_total,  \n      df_m = (m - 1) / gamma^2,\n      df_obs = eta_bar * (eta_bar + 1) * (1 - gamma) / (eta_bar + 3),\n      df = 1 / (1 / df_m + 1 / df_obs),\n      \n      # output\n      se = sqrt(V_total),\n      ci_lower = beta_bar - se * qt(0.975, df = df),\n      ci_upper = beta_bar + se * qt(0.975, df = df)) %>%\n    \n    select(est = beta_bar, se, df, ci_lower, ci_upper) \n  \n  return(pooled)\n  \n}\n```\n:::\n\n\n\nBelow I use the `calc_pooled()` function to pool the results for each of the methods.\n\n## Across\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacross_pooled <- calc_pooled(dat = across_res, est = estimate, se = se, df = df)\nacross_pooled %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|    est|    se|     df| ci_lower| ci_upper|\n|------:|-----:|------:|--------:|--------:|\n| -0.335| 0.038| 93.772|   -0.411|    -0.26|\n\n\n:::\n:::\n\n\n\n## Within\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_pooled <- calc_pooled(dat = within_res, est = estimate, se = se, df = df)\nwithin_pooled %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|    est|    se|     df| ci_lower| ci_upper|\n|------:|-----:|------:|--------:|--------:|\n| -0.356| 0.041| 50.002|   -0.438|   -0.273|\n\n\n:::\n:::\n\n\n\n## Interpretation\n\n### Across\n\nFor students who dropped out, if they drop out of high school, they are expected to score -0.335, 95% CI\\[-0.411, -0.26\\] lower on math score in 2012 compared to if they stayed.\n\n### Within\n\nFor students who dropped out, if they drop out of high school, they are expected to score -0.356, 95% CI\\[-0.438, -0.273\\] lower on math score in 2012 compared to if they stayed.\n\n# Comparing the methods\n\nThe estimates, se and df are different for the results from the two different methods. So which one is better? It's not possible to say based on analysis on one dataset. @hill_2004 and @mitra_comparison_2016 conducted simulation studies comparing the two methods. @hill_2004 found that MI Across performed best in terms of absolute bias and mean squared error compared to all the other methods examined in the study. @mitra_comparison_2016 found that MI Across resulted in greater bias reduction in the estimation of ATT compared to MI Within. For details of the simulation studies please see the articles.\n\n# References\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}