---
title: 'Evaluating the Transition to College Mathematics Course in Texas high schools: Findings from the first year of implementation'
author:
- name: 
    given: James E.
    family: Pustejovsky
- name:
    given: Megha
    family: Joshi
date: 2019-06-30T00:00:00
categories:
- causal inference
- evaluation
- Transition to College Mathematics
links:
- text: White paper
  url: https://www.greatertexasfoundation.org/wp-content/uploads/2021/08/Pustejovsky-Final-2019.pdf
  icon: newspaper
- icon: file-pdf-fill
  text: PDF
  url: /files/TCMC-Eval-Yr-1.pdf
citation: 
  type: report
  collection-title: Greater Texas Foundation White Paper
  publisher: Greater Texas Foundation
  publisher-place: Bryan, TX
  url: https://www.greatertexasfoundation.org/wp-content/uploads/2021/08/Pustejovsky-Final-2019.pdf
---

Texas House Bill 5 introduced requirements that school districts partner with institutions of higher education to provide college preparatory courses in mathematics and English for high school seniors who are not yet college ready. As districts and college partners begin to respond to these provisions, there is a need for empirical research on the effects of different approaches to implementing the college preparatory courses. In response to House Bill 5 requirements, the Charles A. Dana Center has developed a model college preparatory mathematics course, Transition to College Mathematics Course (TCMC), which has been adopted by dozens of school districts across Texas over the past several school years. We examine the effects of TCMC on students’ progress into post-secondary education by comparing students who participated in TCMC during the 2016-17 school year (the first year of implementation) to observationally similar students, either from a previous cohort that did not have access to TCMC or from the same cohort but who did not enroll in the course. We find that, although students who took TCMC graduated at slightly higher rates than comparison students, they had lower rates of enrollment in post-secondary education, driven by lower rates of enrollment in 4-year colleges or universities. Enrollment gradually became more similar over the four semesters following graduation from high school. We find that students who took TCMC were also less likely than students in the comparison group to pass college-level and developmental math courses. Longer-term cumulative outcomes showed stronger reductions in rates of math course passage. However, these results must be interpreted cautiously because we were unable to fully assess and account for students’ college-readiness status at the start of their senior year.
